name: Build and Push NixOS Configuration to Cachix

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config: [thinkpad, desktop]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Print Nix version
        run: nix-instantiate --eval -E '(import <nixpkgs> {}).lib.version'

      # Enable cachix store
      - name: Use Cachix
        uses: cachix/cachix-action@v16
        with:
          name: mysnowfalldots99
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      # Build configs 
      - name: Build config
        run: nix build .#nixosConfigurations.${{ matrix.config }}.config.system.build.toplevel
        # run: nix build .#nixosConfigurations.thinkpad.config.system.build.toplevel
